#!/usr/bin/env python3
"""Sqlantra Text-to-SQL Module - Rule-based with Ollama fallback."""

import re
from typing import Optional, Dict, Any

import llm_client

OLLAMA_URL = llm_client.OLLAMA_URL
MODEL = llm_client.OLLAMA_MODEL


def call_ollama(prompt: str, timeout: int = 60) -> str:
    """Unified LLM call: OpenRouter first, local Ollama fallback."""
    return llm_client.call_llm(prompt, timeout=timeout)


def get_table_schemas() -> str:
    """Get schemas of all tables for context."""
    return """You have access to the following SQLite tables for e-commerce analytics:
 
1. orders (order_id, channel, customer_id, order_date, total_amount, status, raw_data, created_at, updated_at)
   - channel: 'Web', 'App', 'POS', 'API'
   - status: 'pending', 'completed', 'cancelled'
   - total_amount: numeric value (e.g., 2478.00)

2. products (product_id, name, category, price, stock, created_at)
   - category: 'Electronics', 'Audio', 'Footwear', 'Toys'
   - price: numeric value
   - stock: integer quantity available

3. order_items (item_id, order_id, product_id, quantity, unit_price)
   - Links orders to products with quantity and price at time of purchase

4. bronze_orders (id, order_id, raw_data, _source, _ingested_at)
   - Raw order data as ingested from different channels

5. silver_orders (id, order_id, channel, customer_id, total_amount, status, order_date, _curated_at, _domain)
   - Cleaned and standardized order data

6. gold_daily_sales (id, date, channel, total_orders, total_revenue, avg_order_value, _processed_at)
   - Business metrics: daily sales by channel

7. gold_product_performance (id, product_id, product_name, category, total_sold, total_revenue, stock_alert, _processed_at)
   - Product analytics: sales performance and stock alerts

8. gold_customer_360 (id, customer_id, total_orders, total_spent, avg_order_value, customer_segment, clv_prediction, _processed_at)
   - Customer 360: segmentation and lifetime value prediction

9. hitl_approvals (approval_id, action_type, details, requester, status, comment, notification, created_at, responded_at)
   - For high-value order approvals

10. context_memory_log (id, memory_key, memory_value, operation, metadata, created_at)"""


SYSTEM_PROMPT = """You are a text-to-SQL assistant. Your task is to convert natural language queries into SQL statements.

Rules:
1. Only generate SELECT statements (no INSERT, UPDATE, DELETE unless explicitly asked)
2. Use proper SQL syntax for SQLite
3. Return ONLY the SQL query, nothing else
4. If the query is ambiguous, make reasonable assumptions
5. For amount comparisons, use numeric values without dollar signs
6. For status filters, use exact string matches
7. Table and column names are lowercase with underscores
8. The hitl_approvals table does NOT have an amount column - do not query for amount in this table
9. For creating approval requests, you would need to use INSERT statements, but for now focus on SELECT queries only

Always respond with ONLY the SQL query text."""


def post_process_sql(sql: str) -> str:
    """Clean and fix SQL generated by Ollama."""
    sql = sql.strip()

    lines = sql.split("\n")
    clean_lines = []
    for line in lines:
        line = line.strip()
        if (
            line.lower().startswith("error:")
            or line.lower().startswith("note:")
            or line.lower().startswith("sorry")
        ):
            continue
        clean_lines.append(line)
    sql = "\n".join(clean_lines).strip()

    if "hitl_approvals" in sql.lower():
        if "select" not in sql.lower():
            sql = "SELECT * FROM hitl_approvals WHERE status = 'pending'"
        elif "amount" in sql.lower():
            sql = re.sub(
                r"\s+AND\s+amount\s*[=<>!]+\s*[\d\.]+", "", sql, flags=re.IGNORECASE
            )
            sql = re.sub(
                r"\s+WHERE\s+amount\s*[=<>!]+\s*[\d\.]+(\s+AND|$)",
                " WHERE ",
                sql,
                flags=re.IGNORECASE,
            )
            sql = re.sub(r"\s+AND\s+AND\s+", " AND ", sql)
            sql = re.sub(r"\s+OR\s+OR\s+", " OR ", sql)
            sql = re.sub(r"\s+WHERE\s+AND\s+", " WHERE ", sql)
            sql = re.sub(r"\s+WHERE\s+OR\s+", " WHERE ", sql)
            sql = re.sub(r"\s+WHERE\s+\s*$", "", sql)
            if sql.strip().upper().endswith("WHERE"):
                sql = sql.strip()[:-5].strip()

    if "select" not in sql.lower():
        if "pending" in sql.lower() or "pending order" in sql.lower():
            sql = "SELECT * FROM orders WHERE status = 'pending'"
        elif "completed" in sql.lower() or "completed order" in sql.lower():
            sql = "SELECT * FROM orders WHERE status = 'completed'"

    sql = sql.rstrip(";").strip()
    if not sql.upper().startswith("SELECT"):
        sql = "SELECT * FROM orders WHERE status = 'completed'"

    return sql


RULES = [
    (
        r"completed.*order|order.*completed",
        "SELECT * FROM orders WHERE status = 'completed'",
    ),
    (
        r"pending.*order|order.*pending",
        "SELECT * FROM orders WHERE status = 'pending'",
    ),
    (
        r"daily.*sales|sales.*report",
        "SELECT * FROM gold_daily_sales ORDER BY date DESC",
    ),
    (
        r"product.*performance|top.*product",
        "SELECT * FROM gold_product_performance ORDER BY total_revenue DESC",
    ),
    (
        r"customer.*360|customer.*segment",
        "SELECT * FROM gold_customer_360 ORDER BY total_spent DESC",
    ),
    (
        r"order.*over.*?(\d+)",
        "SELECT * FROM orders WHERE total_amount > {0}",
    ),
    (
        r"pipeline|process.*data",
        "SELECT * FROM orders WHERE status = 'completed'",
    ),
]


def rule_based_sql(query: str) -> str:
    """Generate SQL using pattern matching rules for e-commerce."""
    q = query.lower()
    for pattern, template in RULES:
        m = re.search(pattern, q)
        if m:
            groups = m.groups()
            if groups:
                try:
                    amount = int(groups[0].replace(",", ""))
                    return template.format(amount)
                except (ValueError, IndexError):
                    pass
            return template

    if "order" in q:
        return "SELECT * FROM orders WHERE status = 'completed'"
    if "product" in q:
        return "SELECT * FROM products"
    if "sales" in q or "revenue" in q:
        return "SELECT * FROM gold_daily_sales ORDER BY date DESC"
    if "customer" in q:
        return "SELECT * FROM gold_customer_360 ORDER BY total_spent DESC"
    if "pipeline" in q or "process" in q:
        return "SELECT * FROM orders WHERE status = 'completed'"
    return "SELECT * FROM orders WHERE status = 'completed'"


def text_to_sql(natural_language_query: str) -> str:
    """Convert natural language to SQL."""
    try:
        schemas = get_table_schemas()
        prompt = f"""{SYSTEM_PROMPT}

{schemas}

Natural language query: {natural_language_query}

SQL Query:"""

        response = call_ollama(prompt, timeout=30)
        # Check for error before processing
        if response.startswith("Error calling LLM") or not response.strip():
            raise Exception("Ollama unavailable")
        sql = response.strip()
        if sql.startswith("```sql"):
            sql = sql[6:]
        if sql.startswith("```"):
            sql = sql[3:]
        if sql.endswith("```"):
            sql = sql[:-3]
        sql = sql.strip()
        sql = post_process_sql(sql)
        if "select" not in sql.lower():
            raise Exception("No SELECT in response")
        return sql
    except Exception:
        return rule_based_sql(natural_language_query)
    """Convert natural language to SQL and execute."""
    sql = text_to_sql(natural_language_query)
    result = db_module.query_sql(sql)
    return {
        "query": natural_language_query,
        "generated_sql": sql,
        "columns": result.get("columns", []),
        "data": result.get("data", []),
        "row_count": len(result.get("data", [])),
        "error": result.get("error"),
    }


def generate_sql_explanation(sql: str, result_data: list, natural_query: str) -> str:
    """Generate explanation of the SQL query result using Ollama."""
    data_summary = f"Found {len(result_data)} rows"
    if result_data:
        sample = result_data[0] if result_data else {}
        data_summary += f". Sample columns: {', '.join(list(sample.keys())[:5])}"

    prompt = f"""Explain this SQL query and its result in plain English:

Original question: {natural_query}
Generated SQL: {sql}
Result: {data_summary}

Keep explanation brief and clear."""

    return call_ollama(prompt, timeout=30)


if __name__ == "__main__":
    test_queries = [
        "Show all completed orders",
        "List all pending orders",
        "Show daily sales report",
    ]

    for query in test_queries:
        print(f"\nQuery: {query}")
        sql = text_to_sql(query)
        print(f"SQL: {sql}")
